name: Clean up PATH
description: Clean up PATH environment variable on Windows workers

inputs:
  dirs:
    description: Additional paths, separated by a semicolon (;)
    required: false
  default:
    description: Add the default paths
    required: false
    default: 1

runs:
  using: node20
  main: clean.js
  post: restore.js

branding:
  icon: star
  color: green
